customize to new environment
git-svn-id: https://aeon.stsci.edu/ssb/svn/astrolib/trunk/pysynphot@421 90a0a646-be8a-0410-bb88-9290da87bc01

diff --git a/test/auto_test b/test/auto_test
--- a/test/auto_test
+++ b/test/auto_test
@@ -12,18 +12,18 @@
 # d= the name of the directory where you put this script (auto_test)
 d=/eng/ssb/tests/pysynphot/
 
+# exit immediately if a command fails - this means we will leave
+# a non-zero exit code, and so whatever program is running us
+# will know that the test aborted.  This is significantly different
+# from the test failing.
+set -e
+
 #
 # echo each command as it is executed
 set -x 
 
 # who gets failure reports (there are no success reports)
 mailto="sienkiew laidler"
-
-# exit immediately if a command fails - this means we will leave
-# a non-zero exit code, and so whatever program is running us
-# will know that the test aborted.  This is significantly different
-# from the test failing.
-set -e
 
 # add the host name to the log file, because we will be running on
 # multiple systems now.
@@ -75,18 +75,27 @@ then
 fi
 	
 
+mkdir -p run
 cd $d/run
 
 find . ! -mtime -14 -exec rm -f {} ';'
 
 echo $PATH
 
-( cd $d/scripts ; svn update )
+( cd $d/test ; svn update )
 
-python $d/scripts/runtests.py > $t.pysyn_full 2>&1
-status=$?
+# this is in an if so that the exit code can't cause the
+# script to exit.
+if python $d/test/runtests.py > $t.pysyn_full 2>&1
+then
+	status=0
+else
+	status=1
+fi
 
-mv pysyn_summary.log $t.pysyn_summary
+# the host name is in the file name for race avoidance.  if
+# you run the test on the same machine, you might conflict
+mv $host.pysyn_summary.log $t.pysyn_summary
 
 case "$status"
 in
